#!/usr/bin/bash

# Policy Authentication Agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export $(gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)

# https://wiki.hyprland.org/FAQ/#some-of-my-apps-take-a-really-long-time-to-open
# https://gist.github.com/PowerBall253/2dea6ddf6974ba4e5d26c3139ffb7580
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
#dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP --all &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/gcr/ssh

# variables
scripts=~/.scripts

# gsettings
gsettings set org.gnome.desktop.interface gtk-theme 'Tokyonight-Dark-BL-LB'
gsettings set org.gnome.desktop.interface font-name 'CaskaydiaCove Nerd Font 9'
gsettings set org.gnome.desktop.interface icon-theme 'Tokyonight-Moon'
gsettings set org.gnome.desktop.interface cursor-theme 'Sweet-cursors'

# Background
#mpvpaper -vs -o "no-audio loop" eDP-1 LiveWallpaperPC.com-Galactic-River-3840x2160.mp4 --fork
sww init

swww img ~/Pictures/wp/2825810.gif --outputs eDP-1
swww img ~/Pictures/wp/ --output HDMI-A-1

# For nemo
gsettings set org.cinnamon.desktop.default-applications.terminal exec kitty

# notification daemon
swaync &

# waybar
$scripts/launch_waybar &
# $scripts/dynamic &

# music daemon
# mpd &
g4music &

# wallpaper
#$scripts/wall ~/.config/hypr/wallpapers/1.jpg &
waypaper --restore

# effects
# $scripts/tools/rgb &

# Applets
$scripts/appindicator.py &
blueman-applet &
nm-applet --indicator &\

# other
hyprctl setcursor Sweet-cursors 24
wl-paste --watch cliphist store &
notify-send -a aurora "hello $(whoami)" &
libinput-gestures-setup start &

# sleep 1
# mpd-mpris &
# hyprctl dispatch movetoworkspacesilent 2,com.github.neithern.g4music


sleep 1
killall xdg-desktop-portal-hyprland
killall xdg-desktop-portal
/usr/lib/xdg-desktop-portal-hyprland &
sleep 2
/usr/lib/xdg-desktop-portal &
